### ISSUE TITLE
Feature: ignore some js code blocks

### ISSUE THREAD

**Issue by TehShrike** [vesln/jsmd#19]
Sometimes I want JS syntax highlighting for examples of completely theoretical code that doesn't have any point being tested, ala the examples in the [glob-module-file](https://github.com/TehShrike/glob-module-file) readme.

What kind of syntax would be appropriate?

**Comment by ArtskydJ** [comment]
I think there is a way to do this right now. I don't know if you want it to be "officially supported".

rewriter.js runs "js", and "javascript" code blocks. https://github.com/vesln/jsmd/blob/master/lib/jsmd/rewriter.js#L49-L58

GitHub Flavored Markdown uses highlights "js", "javascript", and "node" code blocks as JS syntax.
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2459

So you should be able to do this:

    jsmd will run here
    ```js
    Math.min(1, 2) // => 1
    ```
    
    jsmd will NOT run here
    ```node
    Math.max(1, 2) // => 9999999999
    ```

**Comment by TehShrike** [comment]
oooh, nice, I like that.  That's probably worth noting in the readme.

**Comment by ArtskydJ** [comment]
If noted in the readme, then the tests should assert that '''node ... ''' blocks do not get run.

- [ ] Confirm that the '''node ...''' workaround works
- [ ] Note the workaround in the readme
- [ ] Take a test that confirms that '''node ...''' blocks do not get run

**Comment by TehShrike** [comment]
I tested the workaround here 😅 https://github.com/TehShrike/glob-module-file/pull/4
